spring:
  #数据库配置
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/north
    username: postgres
    password: postgres
  #redis配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    #password: 123456
    timeout: 5000

north:
  updown:
    path: ./upload
  file:
    type: local
    oss:
      endpoint: "oss-cn-hangzhou.aliyuncs.com"
      access-key-id:
      access-key-secret:
      bucket-name: "north-oss"
      prefix-key: "north2"
  email:
    host: "smtp.139.com"
    port: 25
    auth: true
    from: 
    user: 
    pass: 
