server:
  port: 80
#  servlet:
#    context-path: /springboot
#  http2:
#    enabled: true
spring:
  application:
    name: north
  profiles:
    active: 'local'
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB
#satoken权限框架配置
  sa-token:
    token-name: satoken
    activity-timeout: 1800
#swaggerui配置
springdoc:
  packagesToScan: com.north
  swagger-ui:
    docExpansion: none
    filter: true
#mybatis配置
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.north.*.entity
  type-handlers-package: com.north.base.typehandler
  global-config:
    db-config:
      id-type: id_worker_str
      logic-delete-field: isDeleted