server:
  port: 80
#  servlet:
#    context-path: /springboot
#  http2:
#    enabled: true
spring:
  application:
    name: north
  profiles:
    active: 'local'
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

#satoken权限框架配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid

#swaggerui配置
springdoc:
  packagesToScan: com.north
  swagger-ui:
    docExpansion: none
    filter: true
#mybatis配置
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.north.*.entity
  type-handlers-package: com.north.base.typehandler
  global-config:
    db-config:
      id-type: id_worker_str
      logic-delete-field: isDeleted
